version: '3'
services:
  postgres:
    container_name: $POSTGRES_CONTAINER_NAME
    image: 'postgres:12.4'
    restart: always
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_HOST_PORT:5432
    volumes:
      - $POSTGRES_MOUNTED_VOLUME:/var/lib/postgresql/data
  redis:
    container_name: $REDIS_CONTAINER_NAME
    image: 'redis:6.0.8'
    restart: always
    ports:
      - $REDIS_HOST_PORT:6379
    volumes:
      - $REDIS_MOUNTED_VOLUME:/data
    command: redis-server --appendonly yes --requirepass $REDIS_PASSWORD
