version: '3'
services:
  postgres:
    container_name: $PG_CONTAINER_NAME
    image: $PG_IMAGE
    restart: always
    environment:
      - POSTGRES_DB=$PG_DB_NAME
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=$PG_PASSWORD
    ports:
      - $PG_HOST_PORT:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    container_name: $REDIS_CONTAINER_NAME
    image: $REDIS_IMAGE
    restart: always
    ports:
      - $REDIS_HOST_PORT:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass secret_pass
volumes:
  pg_data:
    driver: local
    driver_opts:
      type: none
      device: $PG_MOUNTED_VOLUME
      o: bind
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: $REDIS_MOUNTED_VOLUME
      o: bind
